language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

install:
  - pip install -U poetry
  - poetry install

jobs:
  include:
    - stage: check
      script: flake8 --ignore E501 openpyscad

script:
  - nosetests  --with-coverage --cover-package=openpyscad

after_success:
  - coveralls

stages:
  - check
  - test

notifications:
  email: false